version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    container_name: keycloak
    tty: true
    stdin_open: true
    ports:
      - "18080:8080"
    volumes:
      - ./data/keycloak:/opt/keycloak/data # DB情報等が格納されます
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passwd
    command:
      - start-dev # 開発モードで起動
